apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-rest-api
  template:
    metadata:
      labels:
        app: spring-rest-api
    spec:
      containers:
        - name: spring-rest-api
          image: pierreag/spring:latest
          ports:
            - containerPort: 8585
